# Site settings
title: Data.talk 
email: minh.ng0611@gmail.com
description: "Data Mining Data Visualization Cooking books <3"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lalanguyen.github.io" # the base hostname & protocol for your site
github_username:  lalanguyen
# Build settings
markdown: kramdown
gems:
  - jekyll-archives
jekyll-archives:
  enabled: all
  layout: 'tag_index'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
